### ISSUE TITLE
Error SDK location not found.

### ISSUE THREAD

**Issue by rajeshgoswami2025** [commonsguy/cwac-wakeful#16]
Error:SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

Above messgae is getting when demo ,and demo2 project is being imported.
I set ANDROID_HOME from window console and i have sdk.dir in local.properties file ,like "sdk.dir=C\:\\androidst\\sdk"
Please tell me the solution for it .

**Comment by commonsguy** [comment]
I would recommend that you not load the demo projects until you have your IDE set up. There are [many Android developer support sites](http://www.andglobe.com/) that can assist you, particularly if you tell them what IDE you are using. If you are using Android Studio, you can configure your SDK location via File > Other Settings > Default Project Structure (if you have an IDE window open) or from Configure > Project Defaults > Project Structure (if you are at the "welcome dialog").
