### ISSUE TITLE
What happen if i use WakefulIntentService.scheduleAlarms multiple time to run a background service?

### ISSUE THREAD

**Issue by Ramin-Bateni** [commonsguy/cwac-wakeful#19]
I want run a Background Service. but i want start it when user open main activity OR he/she open widget config OR after boot_completed or each activity to use my App.

Then i wrote the following line of code in several place:
`WakefulIntentService.scheduleAlarms(new DailyListener(), this, false);`

But **i want start just single instance** of `DailyListener` (single alarm | the alarm start my background service if it is required).** I want prevent parallel alarms**.
 
**My question is:**
If the `DailyListener` started and user open multiple time the main activity (run WakefulIntentService.scheduleAlarms multiple time), then the multiple alarm will start parallel or this library guarantee check every things and it just start one instance of target alarm an service?

Is it require to i check the started background services or alarm before this line of code?:
`WakefulIntentService.scheduleAlarms(new DailyListener(), this, false);`

Or is it require to i stop and restart the alarm by some codes?

**Comment by commonsguy** [comment]
This is an issue tracker. It is not a support board. The project `README` has [instructions for getting help](https://github.com/commonsguy/cwac-wakeful#questions).

In general, `scheduleAlarms()` is designed for **very** simple scenarios. I recommend that you follow the [basic usage instructions](https://github.com/commonsguy/cwac-wakeful#basic-usage) and handle `AlarmManager` yourself.
