### ISSUE TITLE
WakefulBroadcastReceiver

### ISSUE THREAD

**Issue by RezaOruji** [commonsguy/cwac-wakeful#20]
@commonsguy does it still make sense to use this library ?
because if I'm not mistaken , WakefulBroadcastReceiver does the same thing ?
http://developer.android.com/training/scheduling/wakelock.html#wakeful

**Comment by commonsguy** [comment]
This is an issue tracker. It is not a support board. The documentation covers [how to ask questions](https://github.com/commonsguy/cwac-wakeful#questions) about the library.

If `WakefulBroadcastReceiver` covers your use case, you are certainly welcome to use it. You probably already have `support-v4` associated with your project anyway, and it saves you a dependency. However, `WakefulBroadcastReceiver` requires a `BroadcastReceiver`, which may not be appropriate in all use cases.
