### ISSUE TITLE
How can I set a timeout value for doWakefulWork?

### ISSUE THREAD

**Issue by GisKook** [commonsguy/cwac-wakeful#21]
Hello,
I want to get location from doWakefulWork,But sometimes,We can not get location.So I need set a timeout value for doWakefulWork.How can I do this?
Thanks,
zhangkai

**Comment by commonsguy** [comment]
This is an issue tracker. It is not a support board. Please read [the documentation](https://github.com/commonsguy/cwac-wakeful#questions) to learn where and how to ask questions.

In your situation, `doWakefulWork()` does not need a timeout. Your location-lookup code needs a timeout, and you need to not use `WakefulIntentService`. Any `IntentService` is designed for a brief synchronous transaction (e.g., disk I/O, network I/O). `IntentService` is not designed for registering a listener and getting a response asynchronously, which is what you need for getting a location. Use your own `Service` (so you control its lifetime) and your own `WakeLock`.
