### ISSUE TITLE
Pass Context reference to getMaxAge()

### ISSUE THREAD

**Issue by alxndrsn** [commonsguy/cwac-wakeful#22]
In my app I allow the user to configure the frequency of the wakeful work which occurs.

It would be very helpful to pass the `ctxt` reference to `getMaxAge()` at https://github.com/commonsguy/cwac-wakeful/blob/84d1a66a9a9a6ce09aa7b84f19e8f3a5ea4b39e1/wakeful/src/com/commonsware/cwac/wakeful/WakefulIntentService.java#L67 so that the value returned can be relative to the user-configured wakeful work frequency.

**Comment by commonsguy** [comment]
I will take a look at this, and your other pull request, this weekend.

**Comment by commonsguy** [comment]
Addressed in v1.1.0 -- thanks!
