### ISSUE TITLE
Alarm does not trigger after force-closing app

### ISSUE THREAD

**Issue by alxndrsn** [commonsguy/cwac-wakeful#28]
max age is set to `pollingInterval * 2`

Seen on:

Make | Model | Model number | Android version 
---|---|---|---
LG | G Play Mini | hi6210sft | 5.1.1

**Comment by commonsguy** [comment]
If by "force-closing", you mean the user pressing Force Stop, this is perfectly normal behavior. All alarms are canceled, and nothing of your app will ever run again, until the user launches an activity of yours from the home screen, or until something else uses an explicit `Intent` to start one of your components.

**Comment by alxndrsn** [comment]
Hey @commonsguy, thanks for clarifying.  So what does this section of `README.markdown` refer to?

> And, you need to implement `getMaxAge(Context)`, which should return the time in milliseconds after which, if we have not seen an alarm go off, we should assume that the alarms were canceled (e.g., application was force-stopped by the user), and should reschedule them.

I read that as meaning that the alarms would be rescheduled and therefore start again automatically, but obviously not :¬\

**Comment by commonsguy** [comment]
I cannot reschedule the alarms. Through `getMaxAge()`, I can help you determine that the alarms stopped firing, that's all.

**Comment by alxndrsn** [comment]
Thanks again for explaining things for me.  I clearly misread the following documentation as meaning something like "max number of milliseconds to wait before re-triggering the alarm":

> And, you need to implement `getMaxAge(Context)`, which should return the time in milliseconds after which, if we have not seen an alarm go off, we should assume that the alarms were canceled (e.g., application was force-stopped by the user), and should reschedule them.

Perhaps it would be clearer to replace _time_ with _timestamp_ or _milliseconds_ with _milliseconds since epoch_.  Alternatively, changing uses of _we_ to _you_ to be more consistent would leave less impression that the library will do the work instead of users having to code that up themselves.
