### ISSUE TITLE
Using JobIntentService alternative and delay caused by Doze

### ISSUE THREAD

**Issue by sjvc** [commonsguy/cwac-wakeful#30]
I have been using your library for years, and now I realized I should not use it when targeting Oreo devices. As you say, JobIntentService looks a good alternative, but as far I know, JobIntentService can delay a task if Android is in Doze mode. My app main purpose is to show reminders (AlarmManager -> BroadcastReceiver -> IntentService -> ShowNotification), so the service should run immediately. I read I can use startForegroundService to manage this issue, but with this approach a wake lock is not acquired. 

What do you think I should do? Should I fork this library and replace startService with startForegroundService? Or is there any way to manage this issue using JobIntentService?

EDIT: What about using WakefulBroadcastReceiver and startForegroundService? It will acquire a wake lock, and run immediately on Android Oreo, right?

EDIT 2: I've just read that WakefulBroadcastReceiver is deprecated on Android Oreo... :(

EDIT 3: What about using [goAsync](https://developer.android.com/reference/android/content/BroadcastReceiver#goAsync())? As the work that should be done takes a short time, I think it can be a solution.

**Comment by commonsguy** [comment]
> JobIntentService can delay a task if Android is in Doze mode

A `JobIntentService` can delay the `onHandleWork()` on Android 8.0+, regardless of environment (e.g., Doze). It uses `JobScheduler`, and we do not have precise control over the timing of jobs.

> My app main purpose is to show reminders (AlarmManager -> BroadcastReceiver -> IntentService -> ShowNotification), so the service should run immediately.

Unless showing a reminder requires I/O, just show the notification from the `BroadcastReceiver`. If it requires I/O, consider `goAsync()`, though you might want to acquire your own `WakeLock` and release it in the `goAsync()` callback. 

> Should I fork this library and replace startService with startForegroundService?

You could, with the appropriate `Build` check, since that method is new to API Level 26.

**Comment by sjvc** [comment]
Thank you for your answer. In my app, I'm showing a reminder, but I'm doing some reads and writes to an sqlite database. I think goAsync it's the way to go.

**Comment by sjvc** [comment]
The docs say this about goAsync:

> Calling goAsync() in your receiver's onReceive() method and passing the BroadcastReceiver.PendingResult to a background thread. This keeps the broadcast active after returning from onReceive(). However, even with this approach the system expects you to finish with the broadcast very quickly (under 10 seconds). It does allow you to move work to another thread to avoid glitching the main thread.

Do you know if it means that the wake lock is kept during 10 seconds or do I need to acquire it explicitly?

**Comment by commonsguy** [comment]
I do not, which is why I recommend holding your own `WakeLock`. Even if it *happens* to keep the `WakeLock`, since none of that `WakeLock` behavior is documented, we have no reason to expect it to be the same in the future.

**Comment by sjvc** [comment]
Good point. I'll do it. Thanks!
